version: '3.1'
services:
  db:
    image: mysql:8.0.37
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - produto-data:/var/lib/mysql

volumes:
  produto-data: